### PR TITLE
Additional color matrix coeffients

### PR DESCRIPTION
**Pull request by kodabb**
Hi,
I've added two matrix coefficients used in old files.
Please let me know if you would like me to change anything.
Thanks

### CODE REVIEW

**Comment by sekrit-twc** [comment]
Please fix the build

**Comment by kodabb** [comment]
whoops sorry, fixed

**Comment by sekrit-twc** [comment]
Squash and it's good.

**Comment by kodabb** [comment]
squashed, and updated the colorspaceapp help text

**Comment by sekrit-twc** [comment]
Approved.

PLEASE NOTE: You must agree to either assign copyright of code to the project owner or license contributions under WTFPL (see COPYING).

**Comment by kodabb** [comment]
I agree to license my contributions under the WTFPL lincense.

**Pull request merged**
